feat(nn-qgrad): added sgd
es-ude/elastic-ai.creator pull request #429
Opened 2024-12-13 17:15 UTC by LeoBuron

Added the new sgd optimizer and meta classes for storing quantization schemes by name. These quantization schemes are initialized for each layer. The quantization schemes are used by the optimizer to determine how to round the values. 

The optimizer recursively iterates over the model and stores all quantization schenes of each layer in a big list. For each quantization scheme the parameter and its gradient are stored together with the information of the quantization scheme in the quantization parameter. 

I added inplace versions of the quantization functions in the fixed point folder, which is used by the optimizer. I am not sure how to make sure that the quantization functions need to be an inplace version.

2024-12-14 16:05 UTC, glencoe requested changes
See comments. The rest looks good to me.

I'm not sure, but i also think adding documentation that explains why you only expect inplace operations would be helpful. I mean we don't really want people or future us to go through the hassle of finding that out again. Maybe a counter example in a test case suffices already.

For what it's worth, we as owners can also bypass the reviews now.

2024-12-14 16:05 UTC, glencoe commented on elasticai/creator/nn/quantized_grads/base_modules/linear.py
>      To keep the weights quantized use only optimizers that apply a quantized update
Don't you even mean

```
IMPORTANT: use only in-place operators for your quantize implementations
```

2025-01-07 14:12 UTC, LeoBuron commented on elasticai/creator/nn/quantized_grads/fixed_point/test_quantize_to_fixed_point.py
> +            -1.5,
I agree. But I don't have the time at the moment

2025-01-07 18:00 UTC, LeoBuron commented on elasticai/creator/nn/quantized_grads/base_modules/batchnorm2d.py
> +        _BatchNorm2d.__init__(
@glencoe Can you give me a better undestanding of what I need to do. What I tried is the following:

´´´python

class A:
    def __init__(self, a, *args, **kwargs):
        self.a = a
        print(f"Init A")

class B:
    def __init__(self, b, *args, **kwargs):
        self.b = b
        print(f"Init B")


class C(A, B):
    def __init__(self, a, b):
        super().__init__(a=a, b=b)


if __name__ == "__main__":
    c = C(1, 2)
    print(c.a)
    print(c.b)

´´´

2025-01-08 13:31 UTC, merged